adds error handling to action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -21,6 +21,16 @@ runs:
       shell: bash
       id: "setup"
       run: |
+        if [ -z "${{ inputs.project_id }}" ]; then
+          echo "::error project_id not set. Please provide as input."
+          exit 1
+        elif [ -z "${{ inputs.identity_provider }}" ]; then
+          echo "::error identity_provider not set. Please provide as input."
+          exit 1
+        elif [ -z "${{ inputs.team }}" ]; then
+          echo "::error team not set. Please provide as input."
+          exit 1
+        fi
         slug=${{ inputs.team }}
         prefix="gar"
         maxLength=30
@@ -43,6 +53,17 @@ runs:
         workload_identity_provider: ${{ inputs.identity_provider }}
         service_account: ${{ steps.setup.outputs.sa_email }}
         token_format: "access_token"
+    - name: "Handle failure"
+      if: ${{ failure() && steps.auth.outcome == 'failure' }}
+      shell: bash
+      run: |
+        cat <<EOF
+        ::error Failed to authenticate to Google Cloud.
+        Ensure that your team has write access to the Github-repository.
+        Ensure that you grant the following persmissions in your workflow:
+          contents: "read"
+          id-token: "write"
+        EOF
     - name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v2
